import React, { useEffect, useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Check, ChevronRight, ClipboardPlus, FileText, FlaskConical, Info, ListFilter, PackageOpen, Scale, ShieldAlert, SlidersHorizontal, TrendingUp } from 'lucide-react';
import { csvCell, displayDate, downloadText, numberText, ProductImage } from './uiUtils';

export const statusNames = { candidate: '可测候选', control: '对照品类', review: '需专项复核', needs_data: '供货证据待补' };
const money = (value) => Number.isFinite(value) ? `¥${numberText(value)}` : '待补';
const statusTone = (status) => ({ candidate: 'badge-emerald', control: 'badge-cyan', review: 'badge-rose', needs_data: 'badge-amber' }[status] || 'badge-cyan');

export function StrategySelector({ ranking, strategy, setStrategy }) {
  const selected = ranking.strategies.find((item) => item.id === strategy) || ranking.strategies[0];
  return <section className="strategy-section"><div className="strategy-label"><SlidersHorizontal size={17} /><strong>按你的测款目标排序</strong></div><div className="strategy-tabs" role="group" aria-label="选品策略">{ranking.strategies.map((item) => <button className={strategy === item.id ? 'active' : ''} key={item.id} onClick={() => setStrategy(item.id)} title={item.description} aria-pressed={strategy === item.id}>{item.name}{strategy === item.id && <Check size={14} />}</button>)}</div><p>{selected?.description}</p></section>;
}

export default function CategoryDashboard({ ranking, strategy, setStrategy, catalog, searchQuery, shortlist, onToggleShortlist, onSelectProduct, onOpenCatalog, onCompare, onEvidence, syncMeta, stale }) {
  const [statusFilter, setStatusFilter] = useState('all');
  const [selectedId, setSelectedId] = useState(null);
  const categories = ranking.categories || [];
  const ranked = categories.filter((item) => item.rank != null).sort((a, b) => a.rank - b.rank);
  const top = ranked.slice(0, 3);
  const filtered = useMemo(() => categories.filter((item) => (statusFilter === 'all' || item.status === statusFilter) && (!searchQuery.trim() || [item.name, ...(item.reasons || []), ...(item.risks || [])].join(' ').toLowerCase().includes(searchQuery.trim().toLowerCase()))), [categories, statusFilter, searchQuery]);
  const selected = categories.find((item) => item.id === selectedId) || ranked[0] || categories[0];
  const strategyName = ranking.strategies.find((item) => item.id === strategy)?.name;
  const selectCategory = (item, scroll = false) => { setSelectedId(item.id); if (scroll) setTimeout(() => document.getElementById('category-inspector')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50); };

  const exportRanking = (format) => {
    const date = new Date().toISOString().slice(0, 10);
    if (format === 'csv') {
      const rows = [['排名', '品类', '策略', '状态', '相对测款适配分', '供应商品数', '供货价中位数CNY', '参考重量中位数g', '供货字段覆盖%', '市场销量', '真实库存', '推荐依据', '风险', '生成时间'], ...categories.map((item) => [item.rank, item.name, strategyName, statusNames[item.status], item.score, item.productCount, item.stats?.entrySupplyPriceCny?.median, item.stats?.entryReferenceWeightG?.median, item.confidence?.supplyCoveragePct, '未核实，不参与评分', '未知', item.reasons?.join('；'), item.risks?.join('；'), ranking.generatedAt])];
      downloadText(`品类优先级-${strategy}-${date}.csv`, rows.map((row) => row.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8');
    } else {
      downloadText(`选品决策简报-${date}.md`, `# 内部选品决策简报\n\n生成时间：${displayDate(ranking.generatedAt, true)}\n策略：${strategyName}\n供货快照最近成功：${displayDate(syncMeta?.lastSuccessAt, true)}\n\n本榜只反映当前供应池与所选策略的相对测款适配度。未验证销量、需求、竞争度、实际结算收入和利润不进入评分；Temu 风控会话中的售罄显示不能证明真实库存。\n\n${categories.map((item) => `## ${item.rank ? `${item.rank}. ` : ''}${item.name}\n\n状态：${statusNames[item.status]}；适配分：${item.score ?? '未评分'}；供应商品：${item.productCount} 款\n\n推荐依据：\n${(item.reasons || []).map((reason) => `- ${reason}`).join('\n')}\n\n风险与缺口：\n${(item.risks || []).map((risk) => `- ${risk}`).join('\n')}\n\n下一步：\n${(item.nextSteps || []).map((step) => `- ${step}`).join('\n')}\n`).join('\n')}\n数据源：${catalog.source}\n`);
    }
  };

  return <div className="ranking-page animate-fade-in">
    <section className="page-heading"><div><span className="eyebrow">CATEGORY INTELLIGENCE · 内部研究</span><h1>把选择，变得有据可依。</h1><p>从现有供应能力出发，找到值得先验证的品类。</p></div><div className="page-heading-actions"><button className="btn btn-outline" onClick={() => exportRanking('csv')}><ArrowDownToLine size={15} />导出排名</button><button className="btn btn-secondary" onClick={() => exportRanking('md')}><FileText size={15} />决策简报</button></div></section>
    <div className="scope-strip"><span><span className="status-dot" />TEMU 美国站 · POD 供货池</span><span>供货更新 {displayDate(syncMeta?.lastSuccessAt)}</span><button onClick={onEvidence}>查看数据口径 <ArrowUpRight size={13} /></button></div>
    <section className="overview-grid"><div><span>本轮比较品类</span><strong>{categories.length}<small>个</small></strong><p>以当前有供货样本的品类为范围</p></div><div><span>有效供应商品</span><strong>{catalog.products.filter((item) => item.active).length}<small>款</small></strong><p>公开目录 · 价格 / SKU / 重量</p></div><div><span>进入候选排名</span><strong>{ranked.length}<small>个品类</small></strong><p>按目标策略评估执行条件</p></div><div className="overview-warning"><span>市场验证状态</span><strong>待补足<ShieldAlert size={20} /></strong><p>销量口径未核实，需求不计分</p></div></section>
    {stale && <div className="stale-banner"><ShieldAlert size={18} /><div><strong>供货数据超过 48 小时未成功更新</strong><span>以下结果基于已保存快照，请先在“数据与方法”检查同步状态。</span></div></div>}
    <StrategySelector ranking={ranking} strategy={strategy} setStrategy={setStrategy} />
    <section><div className="section-title"><div><span className="section-index">01</span><h2>先从这几个方向开始</h2><span className="section-subtitle">优先验证 · 非销量榜</span></div><button className="text-button" onClick={onCompare}>对比候选 <ArrowRight size={15} /></button></div><div className="top-categories">{top.map((category, index) => {
      const representative = category.recommendedProducts?.[0];
      return <article className={`top-category ${index === 0 ? 'top-category-featured' : ''}`} key={category.id}>
        <div className="top-category-heading"><span className="top-rank">0{index + 1}</span><span className="badge badge-emerald">{index === 0 ? '本策略首选' : '可作备选'}</span><strong>{numberText(category.score)}<small> / 100</small></strong></div>
        <div className="category-card-body"><div><h3>{category.name}</h3><p>{category.productCount} 款供货样本</p></div><div className="category-preview"><ProductImage src={representative?.image} alt={representative?.title || category.name} /></div></div>
        <p className="category-summary">{category.reasons?.[0] || '查看供货条件与待验证项'}</p><div className="category-mini-facts"><span>供货中位价<strong>{money(category.stats?.entrySupplyPriceCny?.median)}</strong></span><span>参考重量中位数<strong>{numberText(category.stats?.entryReferenceWeightG?.median)} g</strong></span></div><button className="category-inspect-button" onClick={() => selectCategory(category, true)}>查看推荐依据与行动 <ArrowRight size={16} /></button>
      </article>;
    })}</div></section>
    <div className="evidence-note"><Info size={16} /><span>分数用于安排验证顺序；市场需求、竞争强度和利润仍未知。前列分差很小，建议同批打样后按真实核价与质量再选；小数分差不代表成功率或显著优势。</span><button onClick={onEvidence}>查看依据</button></div>
    <section className="ranking-section"><div className="section-title"><div><span className="section-index">02</span><h2>品类完整排名</h2><span className="section-subtitle">{filtered.length} / {categories.length} 个品类</span></div><label className="compact-select"><ListFilter size={15} /><select aria-label="筛选品类状态" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">全部状态</option>{Object.entries(statusNames).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></label></div>
      <div className="rank-table-wrap"><table className="rank-table"><thead><tr><th>排序 / 品类</th><th>适配分</th><th>供应样本</th><th>供货中位价</th><th>参考重量</th><th>主要依据 / 待验证</th><th><span className="sr-only">查看详情</span></th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className={selected?.id === item.id ? 'selected' : ''}><td><button className="rank-name" onClick={() => selectCategory(item, true)}><span className={`row-rank ${item.rank <= 3 && item.rank ? 'leading' : ''}`}>{item.rank ? String(item.rank).padStart(2, '0') : '—'}</span><span><strong>{item.name}</strong><small>{statusNames[item.status]}{ranking.comparison?.available && item.rankChange != null && <span className={item.rankChange > 0 ? "rank-change up" : "rank-change down"}> · {item.rankChange > 0 ? `↑${item.rankChange}` : item.rankChange < 0 ? `↓${Math.abs(item.rankChange)}` : "名次持平"}</span>}</small></span></button></td><td><div className="score-cell"><strong>{numberText(item.score)}</strong><span><i style={{ width: `${Math.max(0, Math.min(100, item.score || 0))}%` }} /></span></div></td><td><strong>{item.productCount}</strong><small>款</small></td><td>{money(item.stats?.entrySupplyPriceCny?.median)}</td><td>{numberText(item.stats?.entryReferenceWeightG?.median)}<small> g</small></td><td className="rank-reason"><p>{item.reasons?.[0] || '供货证据待补'}</p><small>{item.risks?.[0] || '真实需求与盈利能力尚待验证'}</small></td><td><button className="table-arrow" aria-label={`查看 ${item.name} 推荐依据`} onClick={() => selectCategory(item, true)}><ChevronRight size={17} /></button></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty-state"><PackageOpen size={32} /><h3>没有匹配的品类</h3><p>试试其他关键词，或切换到全部状态。</p><button className="btn btn-outline" onClick={() => setStatusFilter('all')}>重置状态筛选</button></div>}</div>
      <p className="rank-history-note"><Info size={13} />{ranking.comparison?.available ? `与 ${displayDate(ranking.comparison.previousCatalogObservedAt || ranking.comparison.previousGeneratedAt, true)} 的同策略快照比较` : "当前策略尚无前一日可比基线；每天留存新快照后展示名次变化。"}</p><p className="table-footnote">价格为供应池商品参考 SKU 的 CNY 统计，重量用于相对比较；都不等于完整报价或实际运费。对照与复核品类不占推荐名次。</p>
    </section>
    {selected && <CategoryInspector category={selected} ranking={ranking} catalog={catalog} shortlist={shortlist} onToggleShortlist={onToggleShortlist} onSelectProduct={onSelectProduct} onOpenCatalog={onOpenCatalog} />}
  </div>;
}

function CategoryInspector({ category, ranking, catalog, shortlist, onToggleShortlist, onSelectProduct, onOpenCatalog }) {
  const productsById = new Map(catalog.products.map((product) => [String(product.id), product]));
  return <section className="category-inspector" id="category-inspector"><div className="section-title"><div><span className="section-index">03</span><h2>深入了解这个方向</h2></div><span className={`badge ${statusTone(category.status)}`}>{statusNames[category.status]}</span></div><div className="inspector-intro"><div><span className="eyebrow">CATEGORY BRIEF</span><h2>{category.name}</h2><p>{category.sourceCategories?.map((item) => item.name).join(' / ')}</p></div><div className="inspector-score"><strong>{numberText(category.score)}</strong><span>相对测款适配分<br />供货字段覆盖 {numberText(category.confidence?.supplyCoveragePct)}%</span></div></div><div className="inspector-grid"><section><h3><TrendingUp size={17} />为什么先看它</h3><ul className="reason-list">{(category.reasons || []).map((reason) => <li key={reason}><Check size={14} /><span>{reason}</span></li>)}</ul><h3 className="inspector-subheading"><ShieldAlert size={17} />需要留意</h3><ul className="risk-list">{(category.risks || []).map((risk) => <li key={risk}>{risk}</li>)}</ul></section><section><h3><Scale size={17} />分数来自哪里</h3><div className="dimension-bars">{ranking.dimensions.map((dimension) => {
    const detail = category.dimensions?.[dimension.id];
    return <div key={dimension.id}><span>{dimension.name}</span><div><i style={{ width: `${Math.max(0, Math.min(100, detail?.score || 0))}%` }} /></div><strong>{numberText(detail?.score)}</strong><small>权重 {numberText((detail?.weight ?? ranking.strategies.find((item) => item.id === ranking.selectedStrategy)?.weights[dimension.id] ?? 0), 0)}%</small></div>;
  })}</div><p className="muted">工作流与运营复杂度包含未由收益校准的运营判断，其余采用供货字段分档。分数用于安排验证顺序，不代表销量或成功率。</p></section></div><section className="next-steps"><h3><FlaskConical size={18} />下一步怎么做</h3><ol>{(category.nextSteps || []).map((step, index) => <li key={step}><b>{String(index + 1).padStart(2, '0')}</b><p>{step}</p></li>)}</ol></section><section className="representatives"><div className="section-title"><div><h3>从真实供货样本开始</h3><span className="section-subtitle">点开核对完整 SKU</span></div><button className="text-button" onClick={() => onOpenCatalog(category)}>查看类目商品 <ArrowRight size={15} /></button></div><div className="representative-grid">{(category.recommendedProducts || []).slice(0, 3).map((item) => {
    const product = productsById.get(String(item.id));
    return <article className="representative" key={item.id}><button className="representative-image" onClick={() => product && onSelectProduct(product)} disabled={!product} aria-label={`查看商品 ${item.title}`}><ProductImage src={item.image} alt={item.title} /></button><div><button className="representative-title" onClick={() => product && onSelectProduct(product)} disabled={!product}>{item.title}</button><p>参考 SKU · {item.selectedSku?.specLabel || `#${item.selectedSku?.id || item.id}`}</p><div className="representative-facts"><strong>{money(item.selectedSku?.supplyPriceCny)}</strong><span>{numberText(item.selectedSku?.referenceWeightG)} g</span></div><button className={`btn ${shortlist[item.id] ? 'btn-primary' : 'btn-outline'}`} disabled={!product} onClick={() => product && onToggleShortlist(product)}>{shortlist[item.id] ? <Check size={14} /> : <ClipboardPlus size={14} />}{shortlist[item.id] ? '已加入清单' : '加入测款清单'}</button></div></article>;
  })}</div>{category.recommendedProducts?.length === 0 && <p className="muted">暂无适合直接推荐的样本，请先补齐该品类的供货证据。</p>}</section></section>;
}

export function CategoryComparison({ ranking, strategy, setStrategy }) {
  const candidates = ranking.categories.filter((category) => category.rank != null);
  const [ids, setIds] = useState(candidates.slice(0, 3).map((category) => category.id));
  useEffect(() => setIds(candidates.slice(0, 3).map((category) => category.id)), [strategy]);
  const selected = ids.map((id) => ranking.categories.find((category) => category.id === id)).filter(Boolean);
  const facts = [{ name: '本策略名次', value: (item) => item.rank ? `第 ${item.rank} 名` : statusNames[item.status] }, { name: '相对测款适配分', value: (item) => `${numberText(item.score)} / 100` }, { name: '供应商品数', value: (item) => `${item.productCount} 款` }, { name: '供货价中位数', value: (item) => money(item.stats?.entrySupplyPriceCny?.median) }, { name: '参考重量中位数', value: (item) => `${numberText(item.stats?.entryReferenceWeightG?.median)} g` }, { name: '供货字段覆盖', value: (item) => `${numberText(item.confidence?.supplyCoveragePct)}%` }, { name: '已验证市场需求', value: () => '待补，未参与评分' }, ...ranking.dimensions.map((dimension) => ({ name: dimension.name, value: (item) => `${numberText(item.dimensions?.[dimension.id]?.score)} / 100` }))];
  return <div className="comparison-page animate-fade-in"><section className="page-heading"><div><span className="eyebrow">SIDE BY SIDE</span><h1>把候选放在一起看。</h1><p>选择最多三个品类，对照执行条件、风险与验证成本。</p></div></section><StrategySelector ranking={ranking} strategy={strategy} setStrategy={setStrategy} /><div className="compare-scroll"><div className="comparison-grid" style={{ '--compare-columns': Math.max(1, selected.length) }}><div className="comparison-label">比较维度</div>{selected.map((item, index) => <div className="comparison-head" key={index}><span>候选 {index + 1}</span><select aria-label={`选择候选 ${index + 1}`} value={item.id} onChange={(event) => setIds((current) => current.map((id, slot) => slot === index ? event.target.value : id))}>{ranking.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><strong>{numberText(item.score)}<small>适配分</small></strong></div>)}{facts.map((fact) => <React.Fragment key={fact.name}><div className="comparison-label">{fact.name}</div>{selected.map((item, index) => <div className="comparison-value" key={index}>{fact.value(item)}</div>)}</React.Fragment>)}<div className="comparison-label">推荐依据</div>{selected.map((item, index) => <div className="comparison-copy" key={index}><ul>{item.reasons?.slice(0, 3).map((reason) => <li key={reason}>{reason}</li>)}</ul></div>)}<div className="comparison-label">主要风险</div>{selected.map((item, index) => <div className="comparison-copy comparison-risks" key={index}><ul>{item.risks?.slice(0, 3).map((risk) => <li key={risk}>{risk}</li>)}</ul></div>)}<div className="comparison-label">先做哪一步</div>{selected.map((item, index) => <div className="comparison-copy" key={index}>{item.nextSteps?.[0] || '补齐供货与市场证据'}</div>)}</div></div><div className="evidence-note"><Info size={17} /><p>同一份供货快照、同一套策略权重。对比结果不代表市场规模，也不能替代真实核价和小单测试。</p></div></div>;
}
