import React from 'react';
import { AlertTriangle, Check, ChevronRight, Clock3, Database, ExternalLink, FileJson, Info, PauseCircle, RefreshCw, ShieldCheck } from 'lucide-react';
import { displayDate, numberText } from './uiUtils';

const sourceStatus = { success: ['已取得', 'badge-emerald'], partial: ['部分证据', 'badge-amber'], paused: ['暂停采集', 'badge-amber'], rate_limited: ['来源限流', 'badge-rose'], blocked: ['暂不可用', 'badge-rose'], failed: ['更新失败', 'badge-rose'], pending: ['尚未取得', 'badge-amber'] };

export default function EvidenceView({ ranking, syncMeta, dailySync, marketEvidence, errors, onRefresh, refreshing, serverStatus }) {
  const base = import.meta.env.BASE_URL || '/';
  const schedule = dailySync?.schedule;
  return <div className="evidence-page animate-fade-in"><section className="page-heading"><div><span className="eyebrow">EVIDENCE & METHODOLOGY</span><h1>知道什么，也知道缺什么。</h1><p>每份资料保留来源、时间与适用范围，让判断可以复核。</p></div><button className="btn btn-secondary" onClick={onRefresh} disabled={refreshing}><RefreshCw size={16} className={refreshing ? 'spin' : ''} />刷新站点数据</button></section>
    <section className="sync-panel"><div className="sync-panel-heading"><span className="sync-symbol"><RefreshCw size={22} /></span><div><h2>每天同步供应，重新生成排名</h2><p>自动任务更新供应目录并校验数据，站点读取最近发布的有效结果。</p></div><span className={`badge ${schedule?.active ? 'badge-emerald' : 'badge-amber'}`}>{schedule?.active ? '自动任务已配置' : '调度待确认'}</span></div><div className="sync-facts"><div><span>计划执行时间</span><strong>{schedule?.localTime ? `每天 ${schedule.localTime}` : '尚未确认'}</strong><small>{schedule?.timezone || 'Asia/Shanghai'} · 执行可能延迟</small></div><div><span>供应最近成功</span><strong>{displayDate(syncMeta?.lastSuccessAt)}</strong><small>{syncMeta?.detailSuccess ?? '—'} / {syncMeta?.sourceTotal ?? '—'} 款详情成功</small></div><div><span>最近全流程</span><strong>{dailySync?.status === 'success' ? '校验完成' : dailySync?.status === 'failed' ? '运行失败' : '暂无执行记录'}</strong><small>{displayDate(dailySync?.completedAt || dailySync?.lastSuccessAt)}</small></div><div><span>市场采集</span><strong className="amber-text">保持暂停</strong><small>需恢复正常会话并核实销量口径</small></div></div><div className="sync-note"><Info size={15} /><p>{schedule?.note || '计划任务状态以调度器记录为准。刷新按钮重新读取站点数据，不会立即触发源站采集。'} {dailySync?.servingLastKnownGood ? '当前保留上次有效快照。' : ''}</p>{dailySync?.run?.url && <a href={dailySync.run.url} target="_blank" rel="noreferrer">执行记录 <ExternalLink size={13} /></a>}</div>{dailySync?.error && <div className="load-warning"><AlertTriangle size={16} />{dailySync.failureStage ? `${dailySync.failureStage}：` : ''}{dailySync.error}</div>}{serverStatus?.error && <div className="load-warning">本机更新服务：{serverStatus.error}</div>}</section>
    {Object.keys(errors).length > 0 && <div className="load-warning"><AlertTriangle size={18} /><div><strong>部分数据未能读取</strong>{Object.entries(errors).map(([key, message]) => <p key={key}>{key}：{message}</p>)}</div></div>}
    <section><div className="section-title"><div><span className="section-index">01</span><h2>原始证据与覆盖范围</h2></div><span className="section-subtitle">观察时间不随页面生成而刷新</span></div><div className="sources-list">{(marketEvidence?.sources || []).map((source) => {
      const [label, tone] = sourceStatus[source.status] || [source.status || '未知', 'badge-amber'];
      return <article className="source-card" key={source.id}><div className="source-card-heading"><div className="source-icon">{source.status === 'paused' ? <PauseCircle size={20} /> : <Database size={20} />}</div><div><h3>{source.name}</h3><p><Clock3 size={12} />观测于 {displayDate(source.observedAt, true)}</p></div><span className={`badge ${tone}`}>{label}</span></div><p className="source-scope">{source.scope}</p><p className="source-summary">{source.summary}</p><ul className="source-limitations">{source.limitations?.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul>{source.url && <a className="source-evidence-link" href={source.url} target="_blank" rel="noreferrer">查看来源与记录 <ArrowLink /></a>}</article>;
    })}{!marketEvidence?.sources?.length && <div className="empty-state card-glass"><Database size={32} /><h3>市场证据文件尚未就绪</h3><p>供货排名仍可使用，市场需求保持未知。</p></div>}</div></section>
    {!!marketEvidence?.categoryEvidence?.length && <section><div className="section-title"><div><span className="section-index">02</span><h2>现有市场样本能说明什么</h2></div></div>{marketEvidence.categoryEvidence.map((category) => <article className="sample-evidence" key={category.categoryId}><div><span className="badge badge-amber">仅作旁证</span><h3>{category.categoryName}</h3></div><div className="sample-metrics">{category.facts.map((fact) => <div key={fact.label}><span>{fact.label}</span><strong>{fact.value == null ? '未知' : numberText(fact.value, 2)} <small>{fact.value == null ? '' : fact.unit}</small></strong><p>{fact.scope}</p></div>)}</div><ul>{category.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul><p className="sample-next"><ChevronRight size={15} />{category.nextAction}</p></article>)}</section>}
    {ranking && <section className="method-section"><div className="section-title"><div><span className="section-index">03</span><h2>相对适配分如何计算</h2></div><span className="badge badge-cyan">可解释规则</span></div><p className="method-lead">每款选择最便宜的完整 SKU，品类各维度取商品分中位数，再按策略权重汇总已知维度。工作流与运营复杂度包含内部运营判断，尚无历史收益校准；缺失值保持未知。分数只用于安排验证顺序。</p><div className="weight-table-wrap"><table className="weight-table"><thead><tr><th>评分维度</th>{ranking.strategies.map((strategy) => <th key={strategy.id}>{strategy.name}</th>)}</tr></thead><tbody>{ranking.dimensions.map((dimension) => <tr key={dimension.id}><td><strong>{dimension.name}</strong><p>{dimension.description}</p></td>{ranking.strategies.map((strategy) => <td key={strategy.id}>{numberText((strategy.weights?.[dimension.id] || 0), 0)}%</td>)}</tr>)}</tbody></table></div><div className="method-boundaries"><div><ShieldCheck size={19} /><h3>可以据此行动</h3><p>挑选打样方向，比较同 SKU 采购与物流条件，安排小批量验证顺序，跟踪真实测试结果。</p></div><div><AlertTriangle size={19} /><h3>仍需补齐的关键证据</h3><p>同窗需求与竞争样本、真实核价或结算收入、物流报价、合规与质量实测，以及订单、退货和净回款记录。</p></div></div>{marketEvidence?.methodologySources?.map((source) => <p className="method-source" key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.name} <ExternalLink size={12} /></a>：{source.finding}</p>)}</section>}
    <section className="data-downloads"><div><h3><FileJson size={18} />可复核的数据文件</h3><p>生成时间：{displayDate(ranking?.generatedAt, true)} · 原始来源的观测时间见上方；原始响应索引包含 SHA-256 校验值</p></div><div>{['catalog', 'category-rankings', 'market-evidence', 'daily-sync', 'source-evidence', 'ranking-history'].map((name) => <a className="btn btn-outline" key={name} href={`${base}data/${name}.json`} download={`${name}.json`}>{name}.json <ArrowLink /></a>)}</div></section>
  </div>;
}
function ArrowLink() { return <ExternalLink size={13} />; }
